### PR TITLE
Profile page & readme

### PR DESCRIPTION
**Pull request by msdeshmukh009**
**Pages added**
- [Profile page.](https://deploy-preview-5--orion-quiz.netlify.app/pages/profile/profile.html)
- [Readme](https://github.com/msdeshmukh009/orion-quiz/tree/profile-page-%26-readme#orion-quiz)

### CODE REVIEW

**Review by AbhishekkGautam — APPROVED** [review]
Everything looks good to me

**Review by kiranpratyush — APPROVED** [review]
Everything looks good to me

**Comment by RahulKuvlekar** [comment]
looks good you can merge it.

**Review by Kavita539 — APPROVED** [review]
Everything looks good!

**Pull request merged**
