### PR TITLE
Fix pages

### PR DESCRIPTION
**Pull request by msdeshmukh009**
**Major changes**
- Cards Fixed.
- Floating footer in quiz display page fixed.
- Removed unnecessary code.

### CODE REVIEW

**Review by MarkVed17 — APPROVED** [review]
Everything looks good @msdeshmukh009 
You’ve done well with the class names there. Code becomes really simple to interpret while reading. You may proceed.

**Comment by msdeshmukh009** [comment]
> Everything looks good @msdeshmukh009 You’ve done well with the class names there. Code becomes really simple to interpret while reading. You may proceed.

That's good to know. Thanks for the review.

**Review by siddhigate — APPROVED** [review]
Consistent naming & well committed code! Good to merge

**Comment by preethasri** [comment]
good work mahesh

**Pull request merged**
